# Generated by Django 2.1.3 on 2018-11-12 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
